robot:
  name: "google_barkour_vb"
  scene_file: "scene_mjx.xml"
  initial_keyframe: home
  torso_name: torso
  upper_leg_name: upper_leg
  lower_leg_name: lower_leg
  foot_name: foot
  lower_leg_bodies:
    front_left: lower_leg_front_left
    rear_left: lower_leg_hind_left
    front_right: lower_leg_front_right
    rear_right: lower_leg_hind_right
  feet_sites:
    front_left: foot_front_left
    rear_left: foot_hind_left
    front_right: foot_front_right
    rear_right: foot_hind_right
  joints_lower_limits: [-0.7, -1.0, 0.05]
  joints_upper_limits: [0.52, 2.1, 2.1]