robot:
  feet_sites:
    front_left: foot_front_left
    front_right: foot_front_right
    rear_left: foot_hind_left
    rear_right: foot_hind_right
  foot_name: foot
  foot_radius: 0.0175
  initial_keyframe: home
  joints_lower_limits:
  - -0.7
  - -1.0
  - 0.05
  joints_upper_limits:
  - 0.52
  - 2.1
  - 2.1
  lower_leg_bodies:
    front_left: lower_leg_front_left
    front_right: lower_leg_front_right
    rear_left: lower_leg_hind_left
    rear_right: lower_leg_hind_right
  lower_leg_name: lower_leg
  main_body_name: torso
  robot_class: default
  robot_name: google_barkour_vb
  scene_file: scene_mjx.xml
  upper_leg_name: upper_leg
