environment:
  command:
    ranges:
      ang_vel_yaw_max: 0.7
      ang_vel_yaw_min: -0.7
      lin_vel_x_max: 1.5
      lin_vel_x_min: -0.6
      lin_vel_y_max: 0.8
      lin_vel_y_min: -0.8
    resampling_time: 500
  control:
    action_scale: 0.3
  domain_rand:
    kick_interval: 10
    kick_vel: 0.05
  environment_class: TeacherStudent
  observation_noise:
    general_noise: 0.05
  rewards:
    scales:
      action_rate: -0.01
      ang_vel_xy: -0.05
      feet_air_time: 0.2
      foot_slip: -0.1
      lin_vel_z: -2.0
      orientation: -5.0
      stand_still: -0.5
      termination: -1.0
      torques: -0.0002
      tracking_ang_vel: 0.8
      tracking_lin_vel: 1.5
    termination_body_height: 0.18
    tracking_sigma: 0.25
  sim:
    ctrl_dt: 0.02
    override:
      Kd: 0.5
      Kp: 35.0
    sim_dt: 0.004
model:
  latent_size: 16
  model_class: TeacherStudent
  modules:
    adapter:
    - 256
    - 256
    encoder:
    - 256
    - 256
    policy:
    - 256
    - 256
    value:
    - 256
    - 256
training:
  action_repeat: 1
  augment_pixels: false
  batch_size: 256
  deterministic_eval: false
  episode_length: 1000
  log_training_metrics: false
  normalize_observations: true
  num_envs: 8192
  num_eval_envs: 8192
  num_evals: 10
  num_minibatches: 32
  num_resets_per_eval: 0
  num_timesteps: 100000000
  num_updates_per_batch: 4
  optimizer:
    learning_rate: 0.0004
    max_grad_norm: null
  rl_hyperparams:
    clipping_epsilon: 0.3
    discounting: 0.97
    entropy_cost: 0.01
    gae_lambda: 0.95
    normalize_advantage: true
    reward_scaling: 1
  seed: 0
  training_class: PPO
  training_metrics_steps: null
  unroll_length: 20
  use_vision: false
