robot:
  feet_sites:
    front_left: FL_foot
    front_right: FR_foot
    rear_left: RL_foot
    rear_right: RR_foot
  foot_name: foot
  foot_radius: 0.0175
  initial_keyframe: home
  joints_lower_limits:
  - -0.5
  - 0.4
  - -2.3
  joints_upper_limits:
  - 0.5
  - 1.4
  - -0.85
  lower_leg_bodies:
    front_left: FL_calf
    front_right: FR_calf
    rear_left: RL_calf
    rear_right: RR_calf
  lower_leg_name: calf
  main_body_name: base
  robot_class: default
  robot_name: unitree_go2
  scene_file: scene_mjx.xml
  upper_leg_name: thigh
