environment:
  command:
    ranges:
      ang_vel_yaw_max: 0.7
      ang_vel_yaw_min: -0.7
      lin_vel_x_max: 1.5
      lin_vel_x_min: -0.6
      lin_vel_y_max: 0.8
      lin_vel_y_min: -0.8
    resampling_time: 500
  control:
    action_scale: 0.3
  domain_rand:
    kick_interval: 10
    kick_vel: 0.05
  environment_class: QuadrupedVision
  observation_noise:
    general_noise: 0.05
    brightness:
    - 1.0
    - 1.0
  rewards:
    scales:
      action_rate: -0.01
      ang_vel_xy: -0.05
      feet_air_time: 0.2
      foot_slip: -0.1
      lin_vel_z: -2.0
      orientation: -5.0
      stand_still: -0.5
      termination: -1.0
      torques: -0.0002
      tracking_ang_vel: 0.8
      tracking_lin_vel: 1.5
    termination_body_height: 0.18
    tracking_sigma: 0.25
  sim:
    ctrl_dt: 0.02
    override:
      Kd: 0.5
      Kp: 35.0
    sim_dt: 0.004
  use_vision: true
model:
  latent_size: 256
  model_class: TeacherStudentVision
  modules:
    adapter_convolutional:
      - 32
      - 64
      - 64
    adapter_dense:
    - 256
    - 256
    encoder_convolutional:
      - 32
      - 64
      - 64
    encoder_dense:
    - 256
    - 256
    policy:
    - 128
    - 128
    - 128
    - 128
    value:
    - 256
    - 256
    - 256
    - 256
training:
  action_repeat: 1
  batch_size: 256
  discounting: 0.97
  entropy_cost: 0.01
  episode_length: 1000
  learning_rate: 0.0004
  madrona_backend: true
  max_grad_norm: 1.0
  normalize_observations: true
  num_envs: 512
  num_evals: 5
  num_eval_envs: 512
  num_minibatches: 8
  num_timesteps: 1_000_000
  num_updates_per_batch: 8
  reward_scaling: 1
  training_class: PPO_Vision
  unroll_length: 20
vision:
  enabled_cameras:
    - 1
    - 2
  enabled_geom_groups:
    - 0
  gpu_id: 0
  render_batch_size: 256
  render_height: 64
  render_width: 128
  use_rasterizer: false
  vision_class: default
